"""add_user_role_column

Revision ID: 0b06a0bd3723
Revises: 56ac41c6176f
Create Date: 2025-07-08 03:58:15.960820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0b06a0bd3723'
down_revision = '56ac41c6176f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('ADMIN', 'AUDITOR', 'USER', name='userrole')
    userrole_enum.create(op.get_bind())
    
    # Add the column with a default value
    op.add_column('user', sa.Column('role', userrole_enum, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # Drop the enum type
    userrole_enum = sa.Enum('ADMIN', 'AUDITOR', 'USER', name='userrole')
    userrole_enum.drop(op.get_bind())
    # ### end Alembic commands ###
