"""add_tenant_id_to_user_table

Revision ID: 56ac41c6176f
Revises: 579d04d1a71f
Create Date: 2025-07-08 03:36:29.937871

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56ac41c6176f'
down_revision = '579d04d1a71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tenant_id')
    # ### end Alembic commands ###
