"""Remove is_superuser column from user table

Revision ID: 8531f27326c5
Revises: d198aa5166a7
Create Date: 2025-07-09 19:53:24.544801

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8531f27326c5'
down_revision = 'd198aa5166a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_is_superuser', table_name='user')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_user_is_superuser', 'user', ['is_superuser'], unique=False)
    # ### end Alembic commands ###
